### ISSUE TITLE
py311 enablement on ansible devtools projects

### ISSUE THREAD

**Issue by ssbarnea** [ansible/devtools#58]
The goal of this epic is to enable py311 pipelines on all devtools projects ASAP, listing found blockers so we do have enough time to raise upstream bugs or bugfixes. With bit of luck, we should be able to achieve 100% py311 compatibility before python reaches GA.

- [x] ansible-lint
- [x] ansible-compat
- [x] molecule, https://github.com/ansible-community/molecule/pull/3621
  - [x] https://github.com/pytest-dev/pytest-metadata/issues/49
  - [ ] https://github.com/certifi/python-certifi/pull/193
- [x] https://github.com/ansible-community/molecule-podman/pull/127
- [x] https://github.com/ansible-community/molecule-docker/pull/160
- [x] ansible-navigator, block by
  - [x] https://github.com/ansible/ansible-navigator/pull/1256#pullrequestreview-1040280271
  - [x] https://github.com/ansible/ansible-navigator/pull/1251
  - [x] https://github.com/ansible/ansible-navigator/pull/1250
  - [ ] https://github.com/ansible/ansible-runner/pull/1102
  - [ ] several other ansible-runner problems (PRs TBD)
